stages:
  - configure
  - testing
  - deploy

image: alejandroamaro/laravel_icpw2024

services:
  - postgres:13

variables:
  POSTGRES_DB: urbaninmo_api
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root
  DB_CONNECTION: pgsql
  DB_HOST: postgres
  DB_PORT: 5432
  DB_DATABASE: urbaninmo_api
  DB_USERNAME: postgres
  DB_PASSWORD: root

configure-job:
  stage: configure
  script:
    - cd urbaninmo-api
    - cp .env.example .env
    - echo "DB_CONNECTION=$DB_CONNECTION" >> .env
    - echo "DB_HOST=$DB_HOST" >> .env
    - echo "DB_PORT=$DB_PORT" >> .env
    - echo "DB_DATABASE=$DB_DATABASE" >> .env
    - echo "DB_USERNAME=$DB_USERNAME" >> .env
    - echo "DB_PASSWORD=$DB_PASSWORD" >> .env
    - cp .env .env.testing
    - composer install
    - npm install
    - npm run build
    - php artisan key:generate
    - php artisan migrate --seed
    - php artisan storage:link
    - php artisan cache:clear
    - php artisan key:generate --env=testing
  artifacts:
    paths:
      - urbaninmo-api/vendor/
      - urbaninmo-api/.env
      - urbaninmo-api/public/
    expire_in: 1 hour

test-job:
  stage: testing
  script:
    - cd urbaninmo-api
    - php artisan migrate --seed
    - php artisan test --filter=RealEstateControllerTest
    - echo "Testeado"

deploy-job:
  stage: deploy
  only:
    - main
  environment: production
  script:
    - apk update
    - apk add rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - rsync -avz --delete-after -e "ssh -i ~/.ssh/id_rsa" --exclude='.git/' --exclude='node_modules/' --exclude='vendor/' --exclude='storage/' --exclude='public/storage/' --exclude='bootstrap/cache/' --exclude='bootstrap/compiled.php' ./urbaninmo-api/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    - echo "Desplegado"
  tags:
    - UrbanInmo
