stages:
  - configure
  - testing
  - deploy

image: alejandroamaro/laravel_icpw2024

services:
  - php:8.1-fpm
  - postgres:13


variables:
  POSTGRES_DB: urbaninmo_api
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 123

configure-job:
  stage: configure
  script:
    # apk add rsync
    - cp .env.example .env
    - echo DB_CONNECTION=pgsql >> .env
    - echo DB_HOST=postgres >> .env
    - echo DB_PORT=5432 >> .env
    - echo DB_DATABASE=$VAR_DB >> .env
    - echo DB_USERNAME=$VAR_DB_USR >> .env
    - echo DB_PASSWORD=$VAR_DB_PWD >> .env
    - rm .env.testing
    - cp .env .env.testing
    - composer install
    - npm install
    - npm run build
    - php artisan key:generate
    - php artisan migrate --seed
    - php artisan storage:link
    - php artisan cache:clear
    - php artisan key:generate --env=testing
    - echo "=== .env FILE ==="
    - cat .env
    - echo "=== .env.testing FILE ==="
    - cat .env.testing
    - echo "=== LARAVEL MIGRATION STATUS ==="
    - php artisan migrate:status
    - echo "=== TEST DATABASE CHECK ==="
    - php artisan migrate:status --env=testing
  artifacts:
      paths:
        - vendor/
        - .env
        - public/
      expire_in: 1 hour

   

test-job:
  stage: testing
  script:
    - php artisan migrate --seed
    - php artisan test --filter=RealEstateControllerTest
    - echo "Testeado"

deploy-job:
  stage: deploy
  only:
    - main
  environment: production
  script:
    - apk update
    - apk add rsync openssh
    - mkdir -p ~/.ssh
    - echo "Configurando SSH..."
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod -R 600 ~/.ssh/id_rsa
    - echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chown -R root:root ~/.ssh
    #- chmod -R 700 ~/.ssh/authorized_keys
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - cat ~/.ssh/id_rsa
    - echo "Desplegando usando Runner..."
    # ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_HOST
    - rsync -avz --delete-after -e "ssh -i ~/.ssh/id_rsa" --exclude='.git/' --exclude='node_modules/' --exclude='vendor/' --exclude='storage/' --exclude='public/storage/' --exclude='bootstrap/cache/' --exclude='bootstrap/compiled.php' ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    - echo "Desplegado"
  tags:
    - UrbanInmo