version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    user: laravel
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      JWT_SECRET: ${JWT_SECRET}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - internal
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
      # - "443:443" # Habilita esto si usas HTTPS con Let's Encrypt
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - internal
      - public
    depends_on:
      - app
    security_opt:
      - no-new-privileges:true

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    expose:
      - "5432" # No lo exponemos a la red pública

  composer:
    image: composer:latest
    container_name: composer
    user: "197609:197609"  # Usando tu ID de usuario
    volumes:
      - ./:/app
    working_dir: /app
    command: composer install --ignore-platform-reqs --no-interaction
    networks:
      - internal
    depends_on:
      - postgres


volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
    internal: true
  public:
    driver: bridge
